### ISSUE TITLE
pmrp won't start playing any music

### ISSUE THREAD

**Issue by solus-hq** [hakerdefo/pmrp#3]
I'm able to walk through the selection menu and then nothing happens when I finally select any of the menu points.

**Comment by hakerdefo** [comment]
Hi there @tallinn-code,
Open terminal and run the following command,

`mpg123 --control --utf8 --title --preload 1 --buffer 768 "http://50.7.77.179:8022"`

What happens? Does the stream play? If it doesn't play then are there any error messages printed in terminal?

Cheers!!!

**Comment by solus-hq** [comment]
Hello!
I'm currently using ZSH but I think the log below has something to do with mpg123 itself, it doesn't seem to support these options given above.

```
supported options [defaults in brackets]:
   -v    increase verbosity level       -q    quiet (don't print title)
   -t    testmode (no output)           -s    write to stdout
   -w f  write output as WAV file
   -k n  skip first n frames [0]        -n n  decode only n frames [all]
   -c    check range violations         -y    DISABLE resync on errors
   -b n  output buffer: n Kbytes [0]    -f n  change scalefactor [32768]
   -r n  set/force samplerate [auto]
   -o m  select output module           -a d  set audio device
   -2    downsample 1:2 (22 kHz)        -4    downsample 1:4 (11 kHz)
   -d n  play every n'th frame only     -h n  play every frame n times
   -0    decode channel 0 (left) only   -1    decode channel 1 (right) only
   -m    mix both channels (mono)       -p p  use HTTP proxy p [$HTTP_PROXY]
   -@ f  read filenames/URLs from f
   -z    shuffle play (with wildcards)  -Z    random play
   -u a  HTTP authentication string     -E f  Equalizer, data from file
   -C    enable control keys            --no-gapless  not skip junk/padding in mp3s
   -?    this help                      --version  print name + version
```


```
➜  opt mpg123 --control --utf8 --title --preload 1 --buffer 768 "http://50.7.77.179:8022"
mpg123: Unknown option "preload".
```

**Comment by solus-hq** [comment]
The stream can be played when omitting all the given options, though.

**Comment by hakerdefo** [comment]
Hi there @tallinn-code,
Open **pmrp** in your text-editor and change the line no. 6 from,
`PLAYER="mpg123 --control --utf8 --title --preload 1 --buffer 768 --smooth"`
to,
`PLAYER="mpg123 -C -b 768"`
Save the changes.
Run **pmrp**.
**Enjoy**.

Cheers!!!

**Comment by solus-hq** [comment]
Hello!
Did it, but still, no music playing =(
I sometimes get this kind of warning:

```
/usr/local/bin/pmrp: line 90: break: only meaningful in a `for', `while', or `until' loop
```

**Comment by hakerdefo** [comment]
Hi there @tallinn-code,
Thanks for reporting the issue.
I've updated pmrp script so please update your version of pmrp.
And don't forget to replace the line no. 7 of updated version of pmrp,
`PLAYER="mpg123 --control --utf8 --title --preload 1 --buffer 768"`
with
`PLAYER="mpg123 -C -b 768"`

The update and above change should fix the issue on Mac, hopefully!

Cheers!!!

**Comment by solus-hq** [comment]
Hello!

Unfortunately it's still not working =( I select Category, them select Station and terminal screen only flickers every time, but music won't start playing. Maybe I could give you some debug output by launching the script with some additional keys ?

**Comment by hakerdefo** [comment]
Hi @tallinn-code,
From your terminal run pmrp like this,
`sh -x pmrp >> pmrp.log`
This will create a log file **pmrp.log**. Post the details of the log file here please.

Cheers!!!

**Comment by solus-hq** [comment]
[pmrp.log.txt](https://github.com/hakerdefo/pmrp/files/922486/pmrp.log.txt)

And really sorry for missing your reply (should've been checking email)

**Comment by hakerdefo** [comment]
@tallinn-code Sorry for the delayed reply!
Please run following command in your terminal and check what happens? Does the radio stream play? If it doesn't then what is the error message shown?

`mpg123 -C -b 768 "http://50.7.77.179:8022" 2>&1 /dev/null | grep --line-buffered "StreamTitle" | sed -e 's/;.*//' -e 's/.*=//' -e "s/'//g"`

Cheers!!!

**Comment by solus-hq** [comment]
Hello! Unfortunately nothing happens at all. The command runs and there's no output as well as there's no music playing, and my firewall shows no connections being made =(

However when I'm trying to run this:

`➜  ~ mpg123 -C -b 768 "http://50.7.77.179:8022"`

I'm getting the following output

`mpg123: Unknown option "b".`

```
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

usage: mpg123 [option(s)] [file(s) | URL(s) | -]
supported options [defaults in brackets]:
   -v    increase verbosity level       -q    quiet (don't print title)
   -t    testmode (no output)           -s    write to stdout
   -w f  write output as WAV file
   -k n  skip first n frames [0]        -n n  decode only n frames [all]
   -c    check range violations         -y    DISABLE resync on errors
   -b n  output buffer: n Kbytes [0]    -f n  change scalefactor [32768]
   -r n  set/force samplerate [auto]
   -o m  select output module           -a d  set audio device
   -2    downsample 1:2 (22 kHz)        -4    downsample 1:4 (11 kHz)
   -d n  play every n'th frame only     -h n  play every frame n times
   -0    decode channel 0 (left) only   -1    decode channel 1 (right) only
   -m    mix both channels (mono)       -p p  use HTTP proxy p [$HTTP_PROXY]
   -@ f  read filenames/URLs from f
   -z    shuffle play (with wildcards)  -Z    random play
   -u a  HTTP authentication string     -E f  Equalizer, data from file
   -C    enable control keys            --no-gapless  not skip junk/padding in mp3s
   -?    this help                      --version  print name + version
See the manpage mpg123(1) or call mpg123 with --longhelp for more parameters and information.

```
